# Generated by Django 3.2.16 on 2022-11-14 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RI_PET_BLOG', '0002_auto_20221114_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='deathnotice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='RI_PET_BLOG.deathnotice'),
        ),
    ]
